/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#444748",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        outline: "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "inverse-primary": "#c8c6c5",
        secondary: "#725b38",
        "on-secondary": "#ffffff",
        "secondary-container": "#fedeb2",
        "on-secondary-container": "#78603e",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        gold: "#a9803f",
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "1rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        gutter: "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "section-gap": "120px",
        "section-gap-mobile": "64px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      fontFamily: {
        display: ["Syne", "sans-serif"],
        body: ["DM Sans", "sans-serif"],
        "logo-serif": ["'Bodoni Moda'", "serif"],
        "logo-italic": ["'Manrope'", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "300" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "300" }],
        "label-caps": ["12px", { lineHeight: "1.4", letterSpacing: "0.1em", fontWeight: "500" }],
      },
      boxShadow: {
        ambient: "0 10px 30px rgba(26, 26, 26, 0.04)",
        elevated: "0 20px 60px rgba(26, 26, 26, 0.08)",
      },
      transitionTimingFunction: {
        luxe: "cubic-bezier(0.65, 0, 0.35, 1)",
      },
    },
  },
  plugins: [],
};
